### ISSUE TITLE
Can't find generated CSV file

### ISSUE THREAD

**Issue by DavidGoldwasser** [tukuyo/AirPodsPro-Motion-Sampler#1]
This is great, trying it out with AirPods 3 (not Pro). I was able to build it and test on iPhone. I see the information changing as I move my head, and cube view works, but "Export CSV file" doesn't seem to generate a file, has anyone else had this issue?

I'm on iOS 15.2 with iPhone Xs.

**Comment by tukuyo** [comment]
Hi, Thank you for using this repository.
I have confirmed that it works fine in my environment and the motion-data.csv is generated. (iPhone12Pro: iOS 15.2, AirPodsPro)

Just to confirm, Please check your iPhone the 'file' App.
Isn't the csv file stored in the "AirPodsPro" folder?

if its not in that location, please let me know how to reproduce it in detail and provide the following information.
 - Procedure to follow if you run the 'ExportCSV Contents'.
 - Is there an 'AirPodsPro' folder in the 'file' App.
 - Make sure the csv file is generated in the 'AirPodsPro' folder.

Best regards.

---

**Comment by DavidGoldwasser** [comment]
@tukuyo This was user error on my part. I was mistakenly looking in my "iCloud Drive" and not in "My Phone". I now see the CSV files have been generating correctly and I can transfer and read the data from the, sorry for the mix up.
