### ISSUE TITLE
Looking for AirPods Pro

### ISSUE THREAD

**Issue by yunishi3** [tukuyo/AirPodsPro-Motion-Sampler#4]
I just built your app in my iPhone, and opened. That didn't work.
Information View keeps showing "Looking for AirPids Pro" although AirPods connects iPhone.

My environment
- iPhone 13
- iOS 16.1.2
- AirPods Pro 2

Let me know the solution.

**Comment by tukuyo** [comment]
Sorry, I can't find a solution as it is working fine in my environments.

Therefore, my startup procedure and items to be checked are described below.

My startup procedure
1. Wear the AirPods (or Other) with both ears.
2. Confirm that the AirPods (or other) are connected to the iPhone running the app.
3. Launch App(this repository).
4. Tap the 'Information View' cell.
5. The Looking for AirPods display switches to show motion data.
I confirmed that it works even if number 3 comes first.

At the same time as the above, please confirm the following
- Settings > AirPodsPro(This App) > Motion & Fitness Access Permissions.
- Wording in info.plist.(Privacy - Motion Usage Description)

**Comment by yunishi3** [comment]
@tukuyo 
Thank you very much for your quick response.
It worked!! But sometimes it still didn't work. Actually I'm not sure why it worked or not.

The connection might be unstable because there are several apple devices.

Close this issue, thanks.
